"""Package the site for a plain Apache host (HostGator cPanel): one zip whose root holds index.html, src/, data/,
assets/ plus an .htaccess (MIME types for .glb/.hdr/.webp, gzip, cache headers) and VERSION.txt.
Upload the zip into the target folder with the cPanel File Manager and choose Extract; extracting over an older copy
overwrites the files. Run: python tools/build_hostgator_zip.py  (from any folder) -> dist/legacy-heights_<date>.zip"""
import hashlib, os, sys, time, zipfile

SITE = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
DIST = os.path.join(SITE, "dist")
STAMP = time.strftime("%Y-%m-%d_%H%M")
OUT = os.path.join(DIST, f"legacy-heights_{STAMP}.zip")

TOP_FILES = ["index.html", "styles.css", "panel.css"]
TOP_DIRS = ["src", "data", "assets"]
SKIP_SUFFIXES = ("_orig.jpg", "_orig.png", "_thumb.jpg", "_thumb.png", ".psd", ".blend", ".py")

HTACCESS = """# Legacy Heights 3D masterplan - static site (generated by tools/build_hostgator_zip.py)
AddDefaultCharset utf-8
DirectoryIndex index.html

<IfModule mod_mime.c>
  AddType model/gltf-binary .glb
  AddType image/vnd.radiance .hdr
  AddType image/webp .webp
  AddType application/json .json
  AddType image/svg+xml .svg
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain text/javascript application/javascript application/x-javascript application/json image/svg+xml model/gltf-binary image/vnd.radiance
</IfModule>

# every asset URL carries a version query (?v=...), so long caches are safe; the page itself is always revalidated
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresDefault "access plus 7 days"
  ExpiresByType text/html "access plus 0 seconds"
  ExpiresByType application/json "access plus 0 seconds"
  ExpiresByType image/jpeg "access plus 30 days"
  ExpiresByType image/png "access plus 30 days"
  ExpiresByType image/webp "access plus 30 days"
  ExpiresByType model/gltf-binary "access plus 30 days"
  ExpiresByType image/vnd.radiance "access plus 30 days"
</IfModule>

<IfModule mod_headers.c>
  <FilesMatch "\\.(html|json)$">
    Header set Cache-Control "no-cache"
  </FilesMatch>
</IfModule>
"""

LEIAME = """LEGACY HEIGHTS - site 3D (build {stamp})

Como publicar / atualizar no HostGator (cPanel > Gerenciador de Arquivos):
1. Abra a pasta do site (por exemplo public_html/legacy-heights). Na primeira vez, crie a pasta.
2. Clique em "Carregar" (Upload) e envie este arquivo .zip para dentro dessa pasta.
3. Volte ao Gerenciador, clique com o botao direito no .zip > "Extract" (extrair) na propria pasta.
   Os arquivos existentes sao substituidos pelos novos.
4. Apague o .zip depois de extrair (opcional) e abra o site no navegador com Ctrl+F5.

O arquivo .htaccess (oculto: marque "Mostrar arquivos ocultos" nas configuracoes do Gerenciador) define os tipos
de arquivo 3D, a compressao e o cache. O status de vendas continua vindo do Google Apps Script; nada muda nele.
"""


def want(path):
    n = os.path.basename(path)
    return not n.endswith(SKIP_SUFFIXES) and not n.startswith(".")


_seen_dirs = set()
def add_dir(z, name):
    if name in _seen_dirs: return
    _seen_dirs.add(name)
    zi = zipfile.ZipInfo(name + "/", date_time=time.localtime()[:6])
    zi.external_attr = (0o040755 << 16) | 0x10
    z.writestr(zi, b"")


def add_file(z, name, data, mtime=None):
    zi = zipfile.ZipInfo(name, date_time=time.localtime(mtime)[:6])
    zi.compress_type = zipfile.ZIP_DEFLATED
    zi.external_attr = 0o100644 << 16
    z.writestr(zi, data)


def main():
    os.makedirs(DIST, exist_ok=True)
    files = []
    for f in TOP_FILES:
        p = os.path.join(SITE, f)
        if os.path.exists(p): files.append((p, f))
    for d in TOP_DIRS:
        for root, _, names in os.walk(os.path.join(SITE, d)):
            for n in sorted(names):
                p = os.path.join(root, n)
                if want(p): files.append((p, os.path.relpath(p, SITE).replace("\\", "/")))
    h = hashlib.sha1()
    for p, rel in files:
        h.update(rel.encode()); h.update(open(p, "rb").read())
    version = f"{STAMP} {h.hexdigest()[:10]}"
    total = 0
    # explicit Unix permissions (644 files, 755 folders): zips made on Windows carry none, and cPanel then extracts
    # generated entries as 0600 - an unreadable .htaccess makes Apache answer 403 for every URL
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for d in sorted({os.path.dirname(rel) for _, rel in files if "/" in rel}):
            parts = d.split("/")
            for k in range(1, len(parts) + 1): add_dir(z, "/".join(parts[:k]))
        for p, rel in files:
            add_file(z, rel, open(p, "rb").read(), os.path.getmtime(p)); total += os.path.getsize(p)
        add_file(z, ".htaccess", HTACCESS.encode("utf-8"))
        add_file(z, "VERSION.txt", (version + "\n").encode("utf-8"))
        add_file(z, "LEIA-ME.txt", LEIAME.format(stamp=version).encode("utf-8"))
    print(f"written {OUT}\n  {len(files)} files, {total / 1048576:.1f} MB uncompressed, zip {os.path.getsize(OUT) / 1048576:.1f} MB, version {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
