// Legacy Heights — configuration and static data (house types from drawing 25:04/A-01A, Richard Gill Associates)

export const SQFT_PER_M2 = 10.7639;

// House types as tabulated on the Parcel A Extract Plan (gross floor / roof areas per house, sq ft)
export const TYPES = {
  1: { key: 'type1', beds: 2, baths: 2, gfaSqft: 725, roofSqft: 853, units: 1, hex: '#7bd944', label: { en: 'Type 1 House', pt: 'Casa Tipo 1' } },
  2: { key: 'type2', beds: 3, baths: 1, gfaSqft: 839, roofSqft: 970, units: 1, hex: '#d58cff', label: { en: 'Type 2 House', pt: 'Casa Tipo 2' } },
  3: { key: 'type3', beds: 3, baths: 2, gfaSqft: 874, roofSqft: 975, units: 1, hex: '#3e9bff', label: { en: 'Type 3 House', pt: 'Casa Tipo 3' } },
  4: { key: 'type4', beds: 2, baths: 1, gfaSqft: 700, roofSqft: 799, units: 2, hex: '#f0b429', label: { en: 'Type 4 Duplex', pt: 'Duplex Tipo 4' } },
};

// Colour pattern used in the PDF ("padrao_pdf" custom property in Blender) -> house type
export const PDF_TYPE = { azul: 3, verde: 1, lilas: 2, ouro: 4 };

// Blender model index -> building kind (models 1-3 share the single-house body, 4-6 the duplex body)
export const MODEL_KIND = { 1: 'single', 2: 'single', 3: 'single', 4: 'duplex', 5: 'duplex', 6: 'duplex' };

// Facade colour names (Blender materials) -> display names
export const COLOR_LABEL = {
  'Oak Tone': 'Oak Tone',
  'Caramel cloud': 'Caramel Cloud',
  'isle dreamns': 'Isle Dreams',
  'in the blue': 'In the Blue',
  'Marzipan': 'Marzipan',
  'Pinkathon': 'Pinkathon',
};

// Reference renders (assets/img/house_N.jpg). Each render shows one body kind in one facade colour.
export const IMAGES = {
  single: { 'Caramel cloud': 1, 'Oak Tone': 3, 'Marzipan': 4 },
  duplex: { 'isle dreamns': 2, 'in the blue': 5, 'Pinkathon': 6 },
};
export const IMAGE_COLOR = { 1: 'Caramel cloud', 2: 'isle dreamns', 3: 'Oak Tone', 4: 'Marzipan', 5: 'in the blue', 6: 'Pinkathon' };
export const IMAGE_FALLBACK = { single: 3, duplex: 5 };

export function imageFor(kind, color) {
  const exact = IMAGES[kind]?.[color];
  return { index: exact ?? IMAGE_FALLBACK[kind], exact: exact !== undefined };
}

// Commercial backend (Google Apps Script web app, see tools/backend/README.md). Leave empty to run in read-only mode:
// statuses come from data/status.json and the sales actions fall back to e-mail links.
export const BACKEND = {
  url: '',                                   // e.g. 'https://script.google.com/macros/s/AKfy.../exec'
  salesEmail: 'sales@unk.group',             // recipient of the "I'm interested" leads (also used by the mailto fallback)
  pollSeconds: 45,                           // how often visitors refresh the property statuses
};

export const PARCELS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];
// Blender lot numbers ("Terrenos NNN") that are parks: not selectable, no tooltip, filled with trees (besides the
// open-space lots flagged hidden in the export)
export const PARK_LOTS = ['676', '583', '228', '360', '343', '151', '442', '487', '099', '284', '678', '679', '141', '086', '056'];
export const STATUS = {
  available: { hex: '#34a853', label: { en: 'Available', pt: 'Disponível' } },
  reserved: { hex: '#f0a020', label: { en: 'Reserved', pt: 'Reservada' } },
  sold: { hex: '#d93025', label: { en: 'Sold', pt: 'Vendida' } },
};

export const I18N = {
  en: {
    subtitle: 'Lowthers Plantation · Christ Church · Barbados',
    loading: 'Loading the subdivision…',
    houses: 'houses',
    lots: 'lots',
    resetView: 'Overview',
    topView: 'Top view',
    colorByType: 'Colour by type',
    ao: 'AO',
    legend: 'House types',
    search: 'Search house or lot…',
    noResults: 'No match',
    hoverHint: 'Hover a house for a quick summary · click to open details',
    controls: 'Drag to orbit · right-drag / two fingers to pan · scroll to zoom',
    lot: 'Lot',
    house: 'House',
    type: 'Type',
    beds: 'bed',
    baths: 'bath',
    perUnit: 'per unit',
    units: 'units',
    gfa: 'Gross floor area',
    roof: 'Gross roof area',
    lotArea: 'Lot area',
    facade: 'Facade colour',
    model: '3D model',
    openSpace: 'Open space',
    freeLot: 'Lot without a house in the current layout',
    imgNote: 'Reference render shown in',
    imgExact: 'Reference render of this house',
    flyTo: 'Fly to house',
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
    sqft: 'sq ft',
    sqm: 'sq m',
    all: 'All',
    onlyType: 'Only this type',
    showAll: 'Show all types',
    source: 'Areas per drawings 25:04/02D and 25:04/A-01A (Richard Gill Associates Ltd.). Lot areas measured on the 3D model.',
    parcels: 'Phases',
    parcelsHint: 'Show or hide the houses of each parcel',
    propertyId: 'Property ID',
    status: 'Status',
    houseModel: 'House model',
    parcel: 'Parcel',
    floorPlan: 'Floor plan',
    enlarge: 'Enlarge',
    interested: "I'm interested",
    reserve: 'Reserve',
    markSold: 'Mark as sold',
    night: 'Night',
    day: 'Day',
    map: 'Region',
    mapTitle: 'Around Legacy Heights',
    mapHint: 'Road distances and driving times from the site are estimates (OpenStreetMap data, OSRM routing). Click a place to draw its route along the streets; drag to pan, scroll to zoom.',
    leadTitle: 'Tell us you are interested',
    leadIntro: 'The sales team receives your message together with the property reference.',
    name: 'Name',
    email: 'E-mail',
    phone: 'Phone',
    message: 'Message',
    send: 'Send',
    cancel: 'Cancel',
    sending: 'Sending…',
    leadSent: 'Thank you. Your interest was sent to the sales team.',
    leadFailed: 'The message could not be sent. Please try again or e-mail',
    authTitle: 'Authorised staff only',
    authIntro: 'Enter the sales password to change the status of this property.',
    password: 'Password',
    confirm: 'Confirm',
    reserveOk: 'Property reserved.',
    soldOk: 'Property marked as sold.',
    wrongPassword: 'Wrong password.',
    notAvailable: 'This property is no longer available.',
    networkError: 'Could not reach the sales server. Check your connection and try again.',
    readOnly: 'The sales server is not configured yet: statuses are read-only on this page.',
    statusLegend: 'Status',
    inferred: 'parcel inferred from neighbouring lots',
    closeMap: 'Close',
    distance: 'Distance',
    drive: 'Drive',
    min: 'min',
    lastUpdate: 'Status updated',
    release: 'Release (undo)',
    cancelReservation: 'Cancel reservation',
    releaseOk: 'The property is available again.',
    authIntroAdmin: 'Enter the administrator password to change the status of this property.',
    throttled: 'Too many failed attempts. Please wait 10 minutes and try again.',
    busy: 'The sales server is busy, please try again.',
    loadingMap: 'Loading the map…',
    lighting: 'Lighting',
    dusk: 'Dusk',
    clickForRoute: 'Click to see the route by road',
    showRoute: 'Frame the route',
    byRoad: 'by road',
    straightLine: 'straight line',
  },
  pt: {
    subtitle: 'Lowthers Plantation · Christ Church · Barbados',
    loading: 'Carregando o loteamento…',
    houses: 'casas',
    lots: 'lotes',
    resetView: 'Visão geral',
    topView: 'Vista de topo',
    colorByType: 'Cor por tipo',
    ao: 'AO',
    legend: 'Tipos de casa',
    search: 'Buscar casa ou lote…',
    noResults: 'Nada encontrado',
    hoverHint: 'Passe o mouse sobre uma casa para o resumo · clique para abrir os detalhes',
    controls: 'Arraste para orbitar · botão direito / dois dedos para mover · scroll para zoom',
    lot: 'Lote',
    house: 'Casa',
    type: 'Tipo',
    beds: 'quarto(s)',
    baths: 'banho(s)',
    perUnit: 'por unidade',
    units: 'unidades',
    gfa: 'Área construída bruta',
    roof: 'Área bruta de telhado',
    lotArea: 'Área do lote',
    facade: 'Cor da fachada',
    model: 'Modelo 3D',
    openSpace: 'Área verde',
    freeLot: 'Lote sem casa no layout atual',
    imgNote: 'Render de referência na cor',
    imgExact: 'Render de referência desta casa',
    flyTo: 'Ir até a casa',
    close: 'Fechar',
    prev: 'Anterior',
    next: 'Próxima',
    sqft: 'sq ft',
    sqm: 'm²',
    all: 'Todos',
    onlyType: 'Somente este tipo',
    showAll: 'Mostrar todos os tipos',
    source: 'Áreas conforme desenhos 25:04/02D e 25:04/A-01A (Richard Gill Associates Ltd.). Áreas de lote medidas no modelo 3D.',
    parcels: 'Fases',
    parcelsHint: 'Mostre ou oculte as casas de cada parcela',
    propertyId: 'ID do imóvel',
    status: 'Situação',
    houseModel: 'Modelo da casa',
    parcel: 'Parcela',
    floorPlan: 'Planta baixa',
    enlarge: 'Ampliar',
    interested: 'Tenho interesse',
    reserve: 'Reservar',
    markSold: 'Marcar como vendida',
    night: 'Noite',
    day: 'Dia',
    map: 'Região',
    mapTitle: 'Ao redor do Legacy Heights',
    mapHint: 'Distâncias por estrada e tempos de carro a partir do empreendimento são estimativas (dados OpenStreetMap, roteamento OSRM). Clique em um lugar para desenhar o trajeto pelas ruas; arraste para mover, role para ampliar.',
    leadTitle: 'Registrar interesse',
    leadIntro: 'A equipe de vendas recebe sua mensagem junto com a referência do imóvel.',
    name: 'Nome',
    email: 'E-mail',
    phone: 'Telefone',
    message: 'Mensagem',
    send: 'Enviar',
    cancel: 'Cancelar',
    sending: 'Enviando…',
    leadSent: 'Obrigado. Seu interesse foi enviado à equipe de vendas.',
    leadFailed: 'Não foi possível enviar. Tente novamente ou escreva para',
    authTitle: 'Somente equipe autorizada',
    authIntro: 'Digite a senha de vendas para alterar a situação deste imóvel.',
    password: 'Senha',
    confirm: 'Confirmar',
    reserveOk: 'Imóvel reservado.',
    soldOk: 'Imóvel marcado como vendido.',
    wrongPassword: 'Senha incorreta.',
    notAvailable: 'Este imóvel não está mais disponível.',
    networkError: 'Não foi possível falar com o servidor de vendas. Verifique a conexão e tente de novo.',
    readOnly: 'O servidor de vendas ainda não está configurado: as situações são somente leitura nesta página.',
    statusLegend: 'Situação',
    inferred: 'parcela inferida pelos lotes vizinhos',
    closeMap: 'Fechar',
    distance: 'Distância',
    drive: 'De carro',
    min: 'min',
    lastUpdate: 'Situação atualizada',
    release: 'Liberar (desfazer)',
    cancelReservation: 'Cancelar reserva',
    releaseOk: 'O imóvel está disponível novamente.',
    authIntroAdmin: 'Digite a senha de administrador para alterar a situação deste imóvel.',
    throttled: 'Muitas tentativas sem sucesso. Aguarde 10 minutos e tente de novo.',
    busy: 'O servidor de vendas está ocupado, tente novamente.',
    loadingMap: 'Carregando o mapa…',
    lighting: 'Iluminação',
    dusk: 'Entardecer',
    clickForRoute: 'Clique para ver o trajeto pelas ruas',
    showRoute: 'Enquadrar o trajeto',
    byRoad: 'pela estrada',
    straightLine: 'em linha reta',
  },
};
